apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: cicd/spring-petclinic
          ports:
            - containerPort: 8080
              protocol: "TCP"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - spring-petclinic
        from:
          kind: "ImageStreamTag"
          name: "spring-petclinic:latest"
  strategy: 
    type: "Rolling"