apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          imagePullPolicy: Always
          image: image-registry.openshift-image-registry.svc:5000/cicd/spring-petclinic
          ports:
            - containerPort: 8080
              protocol: "TCP"
  # triggers:
  #   - type: "ConfigChange" 
  #   - type: "ImageChange" 
  #     imageChangeParams:
  #       automatic: true
  #       containerNames:
  #         - spring-petclinic
  #       from:
  #         kind: "ImageStreamTag"
  #         namespace: "cicd"
  #         name: "spring-petclinic:latest"