apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    {{ include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
spec:
  selector:
    app: {{ include "app.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        {{ include "app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "app.fullname" . }}
          imagePullPolicy: Always
          image: {{ .Values.imagestream.namespace }}/{{ .Values.imagestream.name }}
          ports:
            - containerPort: 8080
              protocol: "TCP"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ include "app.fullname" . }}
        from:
          kind: "ImageStreamTag"
          namespace: {{ .Values.imagestream.namespace }}
          name: "{{ .Values.imagestream.name }}:{{ .Values.imagestream.version }}"
  strategy: 
    type: "Rolling"